interfaces:
  stateless: ${ components['examples/stateless-component'].interfaces.frontend.url }

components:
  examples/stateless-component: file:./
  examples/echo:
    extends: file:../echo/
    parameters:
      ECHO_TEXT: hello there!
