name: examples/debugging

services:
  api:
    build:
      context: ./
    interfaces:
      main: 8080
    debug:
      command: ["npm", "run", "dev"]
      volumes:
        src:
          host_path: ./src/
          mount_path: /usr/src/app/src

interfaces:
  http: ${{ services.api.interfaces.main.url }}
