version: 2

jobs:
  build:
    docker:
      - image: architectio/architect-cli-base:latest
    steps:
      - checkout
      - run:
          name: Install Docker
          command: curl -sSL https://get.docker.com/ | sh
      - setup_remote_docker
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - run:
          name: npm install
          command: rm -rf node_modules && npm install --unsafe-perm=true && npm link . && npm install --unsafe-perm=true
      - run:
          name: run tests
          command: npm test
