version: 2

jobs:
  build:
    docker:
      - image: architectio/architect-cli-base:latest
        environment:
          API_HOST: $API_HOST
          DEFAULT_REGISTRY_HOST: $DEFAULT_REGISTRY_HOST
          ARCHITECT_USERNAME: $ARCHITECT_USERNAME
          ARCHITECT_PASSWORD: $ARCHITECT_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: clone submodules
          command: git submodule update --recursive --init
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install --unsafe-perm=true
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: npm link
          command: npm link .
      - run:
          name: architect deploy
          # TODO auto login?
          command: |
            architect login
            architect push test/calculator-sample-project/addition-service
            architect deploy architect/addition-service:0.2.0 --environment test --auto_approve
      - run:
          name: run tests
          command: npm test
