name: examples/echo
description: A simple echo http service
keywords:
  - architect-examples
  - echo

parameters:
  ECHO_TEXT:
    default: hello world

services:
  echo-api:
    image: hashicorp/http-echo:latest
    command: ['-listen=:8080', '-text=${{ parameters.ECHO_TEXT }}']
    interfaces:
      http: 8080

interfaces:
  echo:
    description: Serves traffic for the echo service
    url: ${{ services.echo-api.interfaces.http.url }}
