interfaces:
  auth: ${{ components['architect/fusionauth'].interfaces.app.url }}

components:
  architect/fusionauth:
    extends: file:./architect.yml
    parameters:
      DB_NAME: fusionauth
      ROOT_DB_USER: postgres
      ROOT_DB_PASS: architect
      FUSIONAUTH_DB_USER: postgres
      FUSIONAUTH_DB_PASS: architect
      DEFAULT_API_KEY: uirz8xafnvz6kyfji795wbypkinmbp7cf469jz37
      ADMIN_USER_EMAIL: test@architect.io
      ADMIN_USER_PASSWORD: password

    services:
      fusionauth-db:
        interfaces:
          postgres:
            host: host.docker.internal
            protocol: postgresql
            port: 5432
