name: examples/publisher

parameters:
  gcp_project_id:
    description: Name of the GCP project to connect to
    required: true
  publish_topic:
    description: Topic name the service will publish events to
    default: topic

dependencies:
  architect/gcp-pubsub: latest

services:
  api:
    build:
      context: ./
    environment:
      GCP_PROJECT_ID: ${{ parameters.gcp_project_id }}
      PUBSUB_ENDPOINT: ${{ dependencies['architect/gcp-pubsub'].interfaces.pubsub.url }}
      PUBSUB_TOPIC: ${{ parameters.publish_topic }}