name: examples/basic-task
description: Example application that schedules recurring cron tasks

parameters:
  OUTPUT_TEXT:
    description: Example text to output in cron
    default: "Hello world"

tasks:
  date-logger:
    schedule: "*/5 * * * *"
    image: ellerbrock/alpine-bash-curl-ssl # useful public image with bash and curl pre-installed
    command: echo $OUTPUT_TEXT && curl $SERVER_URL
    environment:
      OUTPUT_TEXT: ${{ parameters.OUTPUT_TEXT }}
      SERVER_URL: ${{ services.api.interfaces.main.url }}

services:
  api:
    image: heroku/nodejs-hello-world
    interfaces:
      main: 3000

interfaces:
