name: Test Unsafe Perm Flag

on:
  push:
    branches:
      - 94-gitops-docs

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  register-components:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Architect CLI
        run: npm i -g @architect-io/cli --unsafe-perm
      - name: Architect login
        run: architect login -e ${{ secrets.ARCHITECT_EXAMPLES_ACCT_EMAIL }} -p ${{ secrets.ARCHITECT_EXAMPLES_ACCT_PASSWORD }}
      - name: Architect version
        run: architect --version
